# Data Preprocessing Configuration

# Required columns for the model
# If these columns are missing, they will be created with default values
required_columns:
  # Source columns (from raw data)
  - name: 'equipment_tag'
    default_value: ''
    data_type: 'str'
  - name: 'manufacturer'
    default_value: ''
    data_type: 'str'
  - name: 'model'
    default_value: ''
    data_type: 'str'
  - name: 'category_name'
    default_value: ''
    data_type: 'str'
  - name: 'omniclass_code'
    default_value: ''
    data_type: 'str'
  - name: 'uniformat_code'
    default_value: ''
    data_type: 'str'
  - name: 'masterformat_code'
    default_value: ''
    data_type: 'str'
  - name: 'mcaa_system_category'
    default_value: ''
    data_type: 'str'
  - name: 'building_name'
    default_value: ''
    data_type: 'str'
  - name: 'initial_cost'
    default_value: 0
    data_type: 'float'
  - name: 'condition_score'
    default_value: 0
    data_type: 'float'
  - name: 'CategoryID'
    default_value: 0
    data_type: 'int'
  - name: 'OmniClassID'
    default_value: 0
    data_type: 'int'
  - name: 'UniFormatID'
    default_value: 0
    data_type: 'int'
  - name: 'MasterFormatID'
    default_value: 0
    data_type: 'int'
  - name: 'MCAAID'
    default_value: 0
    data_type: 'int'
  - name: 'LocationID'
    default_value: 0
    data_type: 'int'

  # Target columns (created during feature engineering)
  - name: 'Equipment_Category'
    default_value: ''
    data_type: 'str'
  - name: 'Uniformat_Class'
    default_value: ''
    data_type: 'str'
  - name: 'System_Type'
    default_value: ''
    data_type: 'str'
  - name: 'Equipment_Subcategory'
    default_value: ''
    data_type: 'str'
  - name: 'combined_text'
    default_value: ''
    data_type: 'str'
  - name: 'service_life'
    default_value: 0
    data_type: 'float'
  - name: 'Equipment_Type'
    default_value: ''
    data_type: 'str'
  - name: 'System_Subtype'
    default_value: ''
    data_type: 'str'
  - name: 'OmniClass_ID'
    default_value: ''
    data_type: 'str'
  - name: 'Uniformat_ID'
    default_value: ''
    data_type: 'str'
  - name: 'MasterFormat_ID'
    default_value: ''
    data_type: 'str'
  - name: 'MCAA_ID'
    default_value: 0
    data_type: 'int'
  - name: 'Location_ID'
    default_value: 0
    data_type: 'int'

# Training data configuration
training_data:
  default_path: 'nexusml/data/training_data/fake_training_data.csv'
  encoding: 'utf-8'
  fallback_encoding: 'latin1'
