# Data Preprocessing Configuration

# Required columns for the model
# If these columns are missing, they will be created with default values
required_columns:
  # Source columns (from raw data)
  - name: 'Asset Category'
    default_value: ''
    data_type: 'str'
  - name: 'Equip Name ID'
    default_value: ''
    data_type: 'str'
  - name: 'System Type ID'
    default_value: ''
    data_type: 'str'
  - name: 'Precon System'
    default_value: ''
    data_type: 'str'
  - name: 'Operations System'
    default_value: ''
    data_type: 'str'
  - name: 'Sub System Type'
    default_value: ''
    data_type: 'str'
  - name: 'Sub System ID'
    default_value: ''
    data_type: 'str'
  - name: 'Sub System Class'
    default_value: ''
    data_type: 'str'
  - name: 'Title'
    default_value: ''
    data_type: 'str'
  - name: 'Drawing Abbreviation'
    default_value: ''
    data_type: 'str'
  - name: 'Equipment Size'
    default_value: 0
    data_type: 'float'
  - name: 'Unit'
    default_value: ''
    data_type: 'str'
  - name: 'Service Life'
    default_value: 0
    data_type: 'float'

  # Target columns (created during feature engineering)
  - name: 'Equipment_Category'
    default_value: ''
    data_type: 'str'
  - name: 'Uniformat_Class'
    default_value: ''
    data_type: 'str'
  - name: 'System_Type'
    default_value: ''
    data_type: 'str'
  - name: 'Equipment_Subcategory'
    default_value: ''
    data_type: 'str'
  - name: 'Subsystem_Type'
    default_value: ''
    data_type: 'str'
  - name: 'Subsystem_ID'
    default_value: ''
    data_type: 'str'
  - name: 'combined_text'
    default_value: ''
    data_type: 'str'
  - name: 'size_feature'
    default_value: ''
    data_type: 'str'
  - name: 'service_life'
    default_value: 0
    data_type: 'float'
  - name: 'equipment_size'
    default_value: 0
    data_type: 'float'
  - name: 'Equipment_Type'
    default_value: ''
    data_type: 'str'
  - name: 'System_Subtype'
    default_value: ''
    data_type: 'str'
  - name: 'Full_Classification'
    default_value: ''
    data_type: 'str'

# Training data configuration
training_data:
  default_path: 'ingest/data/eq_ids.csv'
  encoding: 'utf-8'
  fallback_encoding: 'latin1'
