text_combinations:
  - name: 'combined_text'
    columns:
      [
        'equipment_tag',
        'manufacturer',
        'model',
        'category_name',
        'mcaa_system_category',
      ]
    separator: ' '

numeric_columns:
  - name: 'initial_cost'
    new_name: 'initial_cost'
    fill_value: 0
    dtype: 'float'

  - name: 'condition_score'
    new_name: 'service_life' # Renamed to match expected column
    fill_value: 3.0
    dtype: 'float'

hierarchies:
  - new_col: 'Equipment_Type'
    parents: ['category_name', 'equipment_tag']
    separator: '-'

  - new_col: 'System_Subtype'
    parents: ['mcaa_system_category', 'category_name']
    separator: '-'

# Remove the keyword_classifications section that's causing issues
# keyword_classifications:
#   - name: 'Uniformat'
#     source_column: 'combined_text'
#     target_column: 'Uniformat_Class'
#     reference_manager: 'uniformat_keywords'
#     max_results: 1
#     confidence_threshold: 0.0

column_mappings:
  - source: 'category_name'
    target: 'Equipment_Category'

  - source: 'category_name' # Use category_name as a fallback for Uniformat_Class
    target: 'Uniformat_Class'

  - source: 'mcaa_system_category'
    target: 'System_Type'

  - source: 'omniclass_code'
    target: 'OmniClass_ID'

  - source: 'masterformat_code'
    target: 'MasterFormat_ID'

# Simplify the classification systems to avoid errors
classification_systems:
  - name: 'OmniClass'
    source_column: 'omniclass_code'
    target_column: 'OmniClass_ID'
    mapping_type: 'direct' # Changed from 'eav' to 'direct'

  - name: 'Uniformat'
    source_column: 'uniformat_code'
    target_column: 'Uniformat_ID'
    mapping_type: 'direct' # Changed from 'eav' to 'direct'

eav_integration:
  enabled: false # Disabled to simplify the process
