# Production NexusML Configuration File
# Based on the Equipment Classification Production Model (v1.0.0)

feature_engineering:
  # Text combinations from feature_config.yml
  text_combinations:
    - name: 'combined_text'
      columns:
        [
          'equipment_tag',
          'manufacturer',
          'model',
          'category_name',
          'mcaa_system_category',
        ]
      separator: ' '
  
  # Numeric columns from feature_config.yml
  numeric_columns:
    # Removed initial_cost and condition_score as they are not necessary
  
  # Hierarchies from feature_config.yml
  hierarchies:
    - new_col: 'Equipment_Type'
      parents: ['mcaa_system_category', 'category_name']
      separator: '-'
    
    - new_col: 'System_Subtype'
      parents: ['mcaa_system_category', 'category_name']
      separator: '-'
  
  # Column mappings from feature_config.yml
  column_mappings:
    - source: 'category_name'
      target: 'Equipment_Category'
    
    - source: 'uniformat_code'
      target: 'Uniformat_Class'
    
    - source: 'mcaa_system_category'
      target: 'System_Type'
  
  # Classification systems from feature_config.yml
  classification_systems:
    - name: 'OmniClass'
      source_column: 'omniclass_code'
      target_column: 'OmniClass_ID'
      mapping_type: 'direct'
    
    - name: 'MasterFormat'
      source_column: 'masterformat_code'
      target_column: 'MasterFormat_ID'
      mapping_type: 'direct'
    
    - name: 'Uniformat'
      source_column: 'uniformat_code'
      target_column: 'Uniformat_ID'
      mapping_type: 'direct'
  
  # Direct mappings from feature_config.yml
  direct_mappings:
    - source: 'CategoryID'
      target: 'Equipment_Subcategory'
    
    - source: 'OmniClassID'
      target: 'OmniClass_ID'
    
    - source: 'UniFormatID'
      target: 'Uniformat_ID'
    
    - source: 'MasterFormatID'
      target: 'MasterFormat_ID'
    
    - source: 'MCAAID'
      target: 'MCAA_ID'
    
    - source: 'LocationID'
      target: 'Location_ID'
  
  # EAV integration from feature_config.yml
  eav_integration:
    enabled: false

classification:
  # Classification targets from classification_config.yml
  classification_targets:
    - name: 'Equipment_Category'
      description: 'Primary equipment type (e.g., Chiller, Pump, Air Handler)'
      required: true
      master_db:
        table: 'Equipment_Categories'
        field: 'CategoryName'
        id_field: 'CategoryID'
    
    - name: 'Uniformat_Class'
      description: 'Uniformat classification code (e.g., D3040, D2010)'
      required: true
      master_db:
        table: 'UniFormat'
        field: 'UniFormatCode'
        id_field: 'UniFormatID'
    
    - name: 'System_Type'
      description: 'System type (e.g., HVAC, Plumbing)'
      required: true
      master_db:
        table: 'Equipment'
        field: 'System_Type'
    
    - name: 'MasterFormat_Class'
      description: 'MasterFormat classification code'
      required: false
      master_db:
        table: 'MasterFormat'
        field: 'MasterFormatCode'
        id_field: 'MasterFormatID'
  
  # Input field mappings from classification_config.yml
  input_field_mappings:
    - target: 'Asset Category'
      patterns:
        - 'Asset Name'
        - 'Asset Type'
        - 'Equipment Type'
        - 'Equipment Name'
        - 'Equip Name'
        - 'Equip Type'
    
    - target: 'System Type ID'
      patterns:
        - 'Trade'
        - 'System ID'
        - 'Discipline'
    
    - target: 'Precon System'
      patterns:
        - 'System Category'
        - 'System Type'
        - 'System'
    
    - target: 'Equip Name ID'
      patterns:
        - 'Sub System Type'
        - 'Asset Subtype'
        - 'Asset Sub Type'
        - 'Equipment Subtype'

data:
  # Required columns from production_data_config.yml
  required_columns:
    - name: 'equipment_tag'
      default_value: ''
      data_type: 'str'
    - name: 'manufacturer'
      default_value: ''
      data_type: 'str'
    - name: 'model'
      default_value: ''
      data_type: 'str'
    - name: 'category_name'
      default_value: ''
      data_type: 'str'
    - name: 'omniclass_code'
      default_value: ''
      data_type: 'str'
    - name: 'uniformat_code'
      default_value: ''
      data_type: 'str'
    - name: 'masterformat_code'
      default_value: ''
      data_type: 'str'
    - name: 'mcaa_system_category'
      default_value: ''
      data_type: 'str'
    # Removed building_name, initial_cost, and condition_score
    - name: 'CategoryID'
      default_value: 0
      data_type: 'int'
    - name: 'OmniClassID'
      default_value: 0
      data_type: 'int'
    - name: 'UniFormatID'
      default_value: 0
      data_type: 'int'
    - name: 'MasterFormatID'
      default_value: 0
      data_type: 'int'
    - name: 'MCAAID'
      default_value: ''
      data_type: 'str'
    - name: 'LocationID'
      default_value: 0
      data_type: 'int'
    - name: 'Equipment_Category'
      default_value: ''
      data_type: 'str'
    - name: 'Uniformat_Class'
      default_value: ''
      data_type: 'str'
    - name: 'System_Type'
      default_value: ''
      data_type: 'str'
    - name: 'Equipment_Subcategory'
      default_value: ''
      data_type: 'str'
    - name: 'combined_text'
      default_value: ''
      data_type: 'str'
    - name: 'service_life'
      default_value: 0
      data_type: 'float'
    - name: 'Equipment_Type'
      default_value: ''
      data_type: 'str'
    - name: 'System_Subtype'
      default_value: ''
      data_type: 'str'
    - name: 'OmniClass_ID'
      default_value: ''
      data_type: 'str'
    - name: 'Uniformat_ID'
      default_value: ''
      data_type: 'str'
    - name: 'MasterFormat_ID'
      default_value: ''
      data_type: 'str'
    - name: 'MCAA_ID'
      default_value: ''
      data_type: 'str'
    - name: 'Location_ID'
      default_value: 0
      data_type: 'int'
    
    # Additional fields from pricing data system
    - name: 'Precon_System'
      default_value: ''
      data_type: 'str'
    - name: 'Drawing_Abbreviation'
      default_value: ''
      data_type: 'str'
    - name: 'Precon_Tag'
      default_value: ''
      data_type: 'str'
    - name: 'System_Type_ID'
      default_value: ''
      data_type: 'str'
    - name: 'Equip_Name_ID'
      default_value: ''
      data_type: 'str'
    - name: 'Sub_System_ID'
      default_value: ''
      data_type: 'str'
    - name: 'Sub_System_Class'
      default_value: ''
      data_type: 'str'
    - name: 'Class_ID'
      default_value: ''
      data_type: 'str'
    - name: 'Unit'
      default_value: ''
      data_type: 'str'
  
  # MCAAID mapping from production_data_config.yml
  mcaaid_mapping:
    'HVAC Equipment': 'H'
    'Plumbing Equipment': 'P'
    'Mechanical/Sheetmetal': 'SM'
    'Process Cooling Water': 'R'
    'Hot Water Systems': 'H'
    'Refrigeration': 'R'
    'Electrical': 'E'
    'Fire Protection': 'F'
    'Controls': 'C'
  
  # Training data configuration from production_data_config.yml
  training_data:
    default_path: 'nexusml/data/training_data/production_training_data.csv'
    encoding: 'utf-8'
    fallback_encoding: 'latin1'

# Reference data configuration from reference_config.yml
reference_data:
  # Base paths for reference data sources
  paths:
    omniclass: 'nexusml/ingest/reference/omniclass'
    uniformat: 'nexusml/ingest/reference/uniformat'
    masterformat: 'nexusml/ingest/reference/masterformat'
    mcaa_glossary: 'nexusml/ingest/reference/mcaa-glossary'
    mcaa_abbreviations: 'nexusml/ingest/reference/mcaa-glossary'
    smacna: 'nexusml/ingest/reference/smacna-manufacturers'
    ashrae: 'nexusml/ingest/reference/service-life/ashrae'
    energize_denver: 'nexusml/ingest/reference/service-life/energize-denver'
    equipment_taxonomy: 'nexusml/ingest/reference/equipment-taxonomy'
  
  # File patterns for finding reference data files
  file_patterns:
    omniclass: '*.csv'
    uniformat: '*.csv'
    masterformat: '*.csv'
    mcaa_glossary: 'Glossary.csv'
    mcaa_abbreviations: 'Abbreviations.csv'
    smacna: '*.json'
    ashrae: '*.csv'
    energize_denver: '*.csv'
    equipment_taxonomy: '*.csv'
  
  # Column mappings for standardizing reference data
  column_mappings:
    omniclass:
      code: 'OmniClass_Code'
      name: 'OmniClass_Title'
      description: 'Description'
    uniformat:
      code: 'UniFormat Code'
      name: 'UniFormat Title'
      description: 'Description'
    masterformat:
      code: 'MasterFormat Code'
      name: 'MasterFormat Title'
      description: 'Description'
    service_life:
      equipment_type: 'Equipment Type'
      median_years: 'Median Years'
      min_years: 'Min Years'
      max_years: 'Max Years'
      source: 'Source'
    equipment_taxonomy:
      asset_category: 'Asset Category'
      equipment_id: 'Equip Name ID'
      trade: 'Trade'
      title: 'Title'
      drawing_abbreviation: 'Drawing Abbreviation'
      precon_tag: 'Precon Tag'
      system_type_id: 'System Type ID'
      sub_system_type: 'Sub System Type'
      sub_system_id: 'Sub System ID'
      sub_system_class: 'Sub System Class'
      class_id: 'Class ID'
      equipment_size: 'Equipment Size'
      unit: 'Unit'
      service_maintenance_hrs: 'Service Maintenance Hrs'
      service_life: 'Service Life'
  
  # Hierarchical relationships
  hierarchies:
    omniclass:
      separator: '-'
      levels: 3
    uniformat:
      separator: ''
      levels: 4
    masterformat:
      separator: ' '
      levels: 3
  
  # Default values when data is missing
  defaults:
    service_life: 15.0
    confidence: 0.5

# Model configuration
model:
  # Model architecture details from model card
  architecture:
    type: 'RandomForestClassifier'
    text_vectorizer: 'TfidfVectorizer'
    ngram_range: [1, 3]
    hyperparameters:
      n_estimators: 100
      max_depth: 20
      min_samples_split: 2
      min_samples_leaf: 1
      class_weight: 'balanced'
  
  # Output paths
  output:
    model_path: 'outputs/models/equipment_classifier_production.pkl'
    predictions_path: 'outputs/predictions.csv'
    evaluation_path: 'outputs/evaluation_results.json'
  
  # Feature engineering settings
  features:
    text_features:
      - 'combined_text'
    numeric_features:
      - 'service_life'
    categorical_features:
      - 'Equipment_Category'
      - 'System_Type'
  
  # Classification targets
  targets:
    - 'Equipment_Category'
    - 'Uniformat_Class'
    - 'System_Type'
    - 'Equipment_Type'
    - 'System_Subtype'
    - 'MasterFormat_Class'